server:
  port: 8090

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  swagger-ui.urls:
    - name: Book Service
      url: /book-service/v3/api-docs
    - name: User Service
      url: /user-service/v3/api-docs
    - name: Borrowing Service
      url: /borrowing-service/v3/api-docs

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: borrowing-service
          uri: lb://borrowing-service
          predicates:
            - Path=/borrowings/**
        # Ajoute les redirections pour Swagger
        - id: swagger-book
          uri: lb://book-service
          predicates:
            - Path=/book-service/v3/api-docs
        - id: swagger-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
        - id: swagger-borrowing
          uri: lb://borrowing-service
          predicates:
            - Path=/borrowing-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: api-gateway:${server.port}
